version: '3.8'
services:
  cale-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "cale_back"
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/vv
    ports:
      - "8080:8080"



  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vv
      - POSTGRES_PASSWORD=qqq
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data: