version: '3.8'
services:
  cale-backend:
    container_name: spring
    build:
      context: .
      dockerfile: DockerfileSpring
    image: "cale_back"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "5555:5555"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5555
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
      - SPRING_DATASOURCE_PASSWORD=tomato
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_driver-class-name=org.postgresql.Driver

      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=tomato
      - SPRING_FLYWAY_SCHEMAS=public
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres/postgres

      - APPLICATION_SECURITY_JWT_SECRET="Bbzv8whu9su5WYrwBpHFwqPYd7WUGw5bw438vfV6SqP34CgHsAbKlbEEM6QjuTbXWPTXdqM7pnYACgxjsbv2a3FUfMCeNF2T9CTw6"
      - APPLICATION_SECURITY_JWT_TYPE="JWT"
      - APPLICATION_SECURITY_JWT_ISSUER="keypopsh"
      - APPLICATION_SECURITY_JWT_AUDIENCE="users"
      - APPLICATION_SECURITY_JWT_HEADER="Authorization"
      - APPLICATION_SECURITY_JWT_PATH="/"
      - APPLICATION_SECURITY_JWT_EXPIRETIMESECONDS=36000000


  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: DockerfilePostgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=tomato
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data: