spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: tomato
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    user: postgres
    password: tomato
    schemas: public
    url: jdbc:postgresql://localhost:5433/postgres
